import mongoose from "mongoose";
//Creation of the Flow entity
const Schema = mongoose.Schema;

const flowschema = new Schema({
  // also has an id parameter auto-generated by Mongo
  name: {
    type: String,
    require: true,
  },
  // stores first 5 qs, all_questions stores all qs
  questions: [
    {
      type: String,
      require: true,
    },
  ],
  allQuestions: [
    {
      type: String,
      require: true,
    },
  ],
  current_question: {
    type: String,
  },
  transcriptID: {
    type: mongoose.Schema.Types.ObjectId,
    require: true,
  },
  speechList: [{ type: mongoose.Schema.Types.Mixed }],
});

const Flow = mongoose.model("Flow", flowschema);

export default Flow;
