import mongoose from "mongoose";

const Schema = mongoose.Schema;

const flowschema = new Schema({
    // also has an id parameter auto-generated by Mongo
    name:{
        type: String,
        require: true
    },
    questions: [{
        type: String
    }]
})

const Flow = mongoose.model("Flow", flowschema)

export default Flow